### ISSUE TITLE
Candle Error: the candle crate has not been built with cuda support

### ISSUE THREAD

**Issue by jonastemplestein** [mimiquate/candlex#29]
Hi, thanks so much for making this package so quickly!

I'm trying to use candlex in an elixir livebook on a host with an A100 and cuda installed (and working via EXLA backend).

The livebook looks like this

```elixir
# setup cell
Mix.install(
  [
    {:kino_bumblebee, "~> 0.4.0"},
    {:exla, ">= 0.0.0"},
    {:candlex, "~> 0.1.4"}
  ],
  config: [nx: [default_backend: Candlex.Backend]]
)

# subsequent cell

repo =
  {:hf, "codellama/CodeLlama-7b-hf"}

{:ok, model_info} = Bumblebee.load_model(repo, backend: {Candlex.Backend, device: :cuda})
{:ok, tokenizer} = Bumblebee.load_tokenizer(repo)
{:ok, generation_config} = Bumblebee.load_generation_config(repo)

generation_config = Bumblebee.configure(generation_config, max_new_tokens: 100)

serving =
  Bumblebee.Text.generation(model_info, tokenizer, generation_config,
    compile: [batch_size: 1, sequence_length: 1028],
    stream: false,
    defn_options: [compiler: EXLA, lazy_transfers: :never],
    preallocate_params: true
  )

Kino.start_child({Nx.Serving, name: Codellama, serving: serving})

prompt = "<PRE> #fibonnaci in elixir <SUF>Fibby.fib(5) <MID>\n"

Nx.Serving.batched_run(CodeLlama, prompt)
```

I get the error `Candle Error: the candle crate has not been built with cuda support` when calling Bumblebee.load_model. How would I go about installing the correct crate? Sorry, I'm a total rust and rustler newbie.

Any help is much appreciated <3

Other than that, would you expect the above to work and with performance on-par with the EXLA backend?

**Comment by grzuy** [comment]
Hi @jonastemplestein,

Thanks for trying it out and reporting back.

To have candlex target CUDA you'd need to run your elixir app with `CANDLEX_NIF_TARGET=cuda`.
However, I think when running file exs script with `Mix.install` like in your case here the env var won't work.
Alternatively, you need to directly config the package in `Mix.install`, something like:

```diff
   config: [
     nx: [default_backend: Candlex.Backend],
+    candlex: [use_cuda: true]
   ]
```

**Comment by grzuy** [comment]
> Other than that, would you expect the above to work and with performance on-par with the EXLA backend?

Not yet on-par in functionality nor performance.
Still early compared to more mature EXLA.
